# Generated by Django 4.2.20 on 2025-05-05 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workhub", "0002_jobpost"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobpost",
            name="required_tech_stack",
            field=models.ManyToManyField(blank=True, to="workhub.techstack"),
        ),
    ]
