# Generated by Django 4.2.20 on 2025-05-05 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workhub", "0003_jobpost_required_tech_stack"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="jobpost",
            name="required_tech_stack",
        ),
        migrations.AddField(
            model_name="jobpost",
            name="tech_stack",
            field=models.ManyToManyField(blank=True, to="workhub.techstack"),
        ),
    ]
