# Generated by Django 4.2.20 on 2025-05-05 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workhub", "0004_remove_jobpost_required_tech_stack_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobpost",
            name="applicants",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="jobpost",
            name="views",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
